onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Literal /main/DUT/g_simulation
add wave -noupdate -format Literal /main/DUT/g_virtual_uart
add wave -noupdate -format Literal /main/DUT/g_ep_rxbuf_size_log2
add wave -noupdate -format Literal /main/DUT/g_dpram_initf
add wave -noupdate -format Literal /main/DUT/g_dpram_size
add wave -noupdate -format Literal /main/DUT/g_num_gpio
add wave -noupdate -format Logic /main/DUT/clk_sys_i
add wave -noupdate -format Logic /main/DUT/clk_dmtd_i
add wave -noupdate -format Logic /main/DUT/clk_ref_i
add wave -noupdate -format Logic /main/DUT/rst_n_i
add wave -noupdate -format Logic /main/DUT/pps_p_o
add wave -noupdate -format Logic /main/DUT/dac_hpll_load_p1_o
add wave -noupdate -format Literal /main/DUT/dac_hpll_data_o
add wave -noupdate -format Logic /main/DUT/dac_dpll_load_p1_o
add wave -noupdate -format Literal /main/DUT/dac_dpll_data_o
add wave -noupdate -format Logic /main/DUT/phy_ref_clk_i
add wave -noupdate -format Literal /main/DUT/phy_tx_data_o
add wave -noupdate -format Logic /main/DUT/phy_tx_k_o
add wave -noupdate -format Logic /main/DUT/phy_tx_disparity_i
add wave -noupdate -format Logic /main/DUT/phy_tx_enc_err_i
add wave -noupdate -format Literal /main/DUT/phy_rx_data_i
add wave -noupdate -format Logic /main/DUT/phy_rx_rbclk_i
add wave -noupdate -format Logic /main/DUT/phy_rx_k_i
add wave -noupdate -format Logic /main/DUT/phy_rx_enc_err_i
add wave -noupdate -format Literal /main/DUT/phy_rx_bitslide_i
add wave -noupdate -format Logic /main/DUT/phy_rst_o
add wave -noupdate -format Logic /main/DUT/phy_loopen_o
add wave -noupdate -format Literal /main/DUT/gpio_o
add wave -noupdate -format Literal /main/DUT/gpio_i
add wave -noupdate -format Literal /main/DUT/gpio_dir_o
add wave -noupdate -format Logic /main/DUT/uart_rxd_i
add wave -noupdate -format Logic /main/DUT/uart_txd_o
add wave -noupdate -format Literal /main/DUT/wb_addr_i
add wave -noupdate -format Literal /main/DUT/wb_data_i
add wave -noupdate -format Literal /main/DUT/wb_data_o
add wave -noupdate -format Literal /main/DUT/wb_sel_i
add wave -noupdate -format Logic /main/DUT/wb_we_i
add wave -noupdate -format Logic /main/DUT/wb_cyc_i
add wave -noupdate -format Logic /main/DUT/wb_stb_i
add wave -noupdate -format Logic /main/DUT/wb_ack_o
add wave -noupdate -format Logic /main/DUT/genrest_n
add wave -noupdate -format Literal /main/DUT/dio_o
add wave -noupdate -format Logic /main/DUT/s_rst
add wave -noupdate -format Logic /main/DUT/s_rst_n
add wave -noupdate -format Logic /main/DUT/s_pps_csync
add wave -noupdate -format Literal /main/DUT/ppsg_wb_i
add wave -noupdate -format Literal /main/DUT/ppsg_wb_o
add wave -noupdate -format Literal /main/DUT/hpll_wb_i
add wave -noupdate -format Literal /main/DUT/hpll_wb_o
add wave -noupdate -format Literal /main/DUT/dpll_wb_i
add wave -noupdate -format Literal /main/DUT/dpll_wb_o
add wave -noupdate -format Literal /main/DUT/s_ep_rx_data_o
add wave -noupdate -format Literal /main/DUT/s_ep_rx_ctrl_o
add wave -noupdate -format Logic /main/DUT/s_ep_rx_bytesel_o
add wave -noupdate -format Logic /main/DUT/s_ep_rx_sof_p1_o
add wave -noupdate -format Logic /main/DUT/s_ep_rx_eof_p1_o
add wave -noupdate -format Logic /main/DUT/s_ep_rx_dreq_i
add wave -noupdate -format Logic /main/DUT/s_ep_rx_valid_o
add wave -noupdate -format Logic /main/DUT/s_ep_rx_rerror_p1_o
add wave -noupdate -format Literal /main/DUT/s_ep_tx_data_i
add wave -noupdate -format Literal /main/DUT/s_ep_tx_ctrl_i
add wave -noupdate -format Logic /main/DUT/s_ep_tx_bytesel_i
add wave -noupdate -format Logic /main/DUT/s_ep_tx_sof_p1_i
add wave -noupdate -format Logic /main/DUT/s_ep_tx_eof_p1_i
add wave -noupdate -format Logic /main/DUT/s_ep_tx_dreq_o
add wave -noupdate -format Logic /main/DUT/s_ep_tx_valid_i
add wave -noupdate -format Logic /main/DUT/s_ep_tx_terror_p1_o
add wave -noupdate -format Literal /main/DUT/txtsu_port_id_o
add wave -noupdate -format Literal /main/DUT/txtsu_frame_id_o
add wave -noupdate -format Literal /main/DUT/txtsu_tsval_o
add wave -noupdate -format Logic /main/DUT/txtsu_valid_o
add wave -noupdate -format Logic /main/DUT/txtsu_ack_i
add wave -noupdate -format Literal /main/DUT/ep_wb_i
add wave -noupdate -format Literal /main/DUT/ep_wb_o
add wave -noupdate -format Literal /main/DUT/s_gtp_tx_data_i
add wave -noupdate -format Logic /main/DUT/s_gtp_tx_k_i
add wave -noupdate -format Logic /main/DUT/s_gtp_tx_disparity_o
add wave -noupdate -format Logic /main/DUT/s_gtp_tx_enc_err_o
add wave -noupdate -format Literal /main/DUT/s_gtp_rx_data_o
add wave -noupdate -format Logic /main/DUT/s_gtp_rx_rbclk_o
add wave -noupdate -format Logic /main/DUT/s_gtp_rx_k_o
add wave -noupdate -format Logic /main/DUT/s_gtp_rx_enc_err_o
add wave -noupdate -format Literal /main/DUT/s_gtp_rx_bitslide_o
add wave -noupdate -format Logic /main/DUT/s_gtp_rst_i
add wave -noupdate -format Logic /main/DUT/s_gtp_loopen_i
add wave -noupdate -format Literal /main/DUT/s_mnic_mem_data_o
add wave -noupdate -format Literal /main/DUT/s_mnic_mem_addr_o
add wave -noupdate -format Literal /main/DUT/s_mnic_mem_data_i
add wave -noupdate -format Logic /main/DUT/s_mnic_mem_wr_o
add wave -noupdate -format Literal /main/DUT/mnic_wb_i
add wave -noupdate -format Literal /main/DUT/mnic_wb_o
add wave -noupdate -format Logic /main/DUT/mnic_wb_irq_o
add wave -noupdate -format Literal /main/DUT/zpu_wb_i
add wave -noupdate -format Literal /main/DUT/zpu_wb_o
add wave -noupdate -format Literal /main/DUT/lm32_iwb_i
add wave -noupdate -format Literal /main/DUT/lm32_iwb_o
add wave -noupdate -format Literal /main/DUT/lm32_dwb_i
add wave -noupdate -format Literal /main/DUT/lm32_dwb_o
add wave -noupdate -format Literal /main/DUT/dpram_wb_i
add wave -noupdate -format Literal /main/DUT/dpram_wb_o
add wave -noupdate -format Literal /main/DUT/periph_wb_i
add wave -noupdate -format Literal /main/DUT/periph_wb_o
add wave -noupdate -format Literal /main/DUT/wbm_unused_i
add wave -noupdate -format Literal /main/DUT/wbs_unused_i
add wave -noupdate -format Literal /main/DUT/cnx_master_i
add wave -noupdate -format Literal /main/DUT/cnx_master_o
add wave -noupdate -format Literal /main/DUT/cnx_slave_i
add wave -noupdate -format Literal /main/DUT/cnx_slave_o
add wave -noupdate -format Literal /main/DUT/ext_wb_i
add wave -noupdate -format Literal /main/DUT/ext_wb_o
add wave -noupdate -format Literal /main/DUT/rst_wb_addr_o
add wave -noupdate -format Literal /main/DUT/rst_wb_data_i
add wave -noupdate -format Literal /main/DUT/rst_wb_data_o
add wave -noupdate -format Literal /main/DUT/rst_wb_sel_o
add wave -noupdate -format Logic /main/DUT/rst_wb_we_o
add wave -noupdate -format Logic /main/DUT/rst_wb_cyc_o
add wave -noupdate -format Logic /main/DUT/rst_wb_stb_o
add wave -noupdate -format Logic /main/DUT/rst_wb_ack_i
add wave -noupdate -format Logic /main/DUT/genrst_n
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/g_phy_mode
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/rst_n_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/clk_sys_i
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_data_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_bytesel_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_sof_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_eof_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_abort_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_error_p_o
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_busy_o
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_valid_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/pcs_fifo_almostfull_o
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/mdio_mcr_pdown_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/mdio_wr_spec_tx_cal_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/an_tx_en_i
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/an_tx_val_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/timestamp_stb_p_o
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/rmon_tx_underrun_o
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/gtp_tx_clk_i
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/gtp_tx_data_o
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/gtp_tx_k_o
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/gtp_tx_disparity_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/gtp_tx_enc_err_i
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tbi_txclk_i
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tbi_txdata_o
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_is_k
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_enc_err
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_disparity
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_catch_disparity
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_odata_reg
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_state
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_preamble_cntr
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_cr_alternate
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_rdreq
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_newframe
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_data_in
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_data_out
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_msb
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_lsb
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_singlebyte
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_end
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_start
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_rdempty
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_almostempty
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_abort
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_rdreq_toggle
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_odd_length
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_clear_n
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/fifo_rdy
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_busy
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_error
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/reset_synced_txclk
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/txdata_encoded
add wave -noupdate -format Literal /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/txdata_encoded_d0
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/mdio_mcr_pdown_synced
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_clk
add wave -noupdate -format Logic /main/DUT/wr_endpoint/u_pcs_1000basex/u_tx_pcs/tx_fifo_enough_data
add wave -noupdate -format Literal /main/DUT/rst_wb_i
add wave -noupdate -format Literal /main/DUT/rst_wb_o
add wave -noupdate -format Literal /main/DUT/hpll_auxout
add wave -noupdate -format Literal /main/DUT/dmpll_auxout
add wave -noupdate -format Literal /main/DUT/clk_ref_slv
add wave -noupdate -format Literal /main/DUT/clk_rx_slv
add wave -noupdate -format Literal /main/DUT/s_dummy_addr
add wave -noupdate -format Logic /main/DUT/rst_n_inv
add wave -noupdate -format Logic /main/DUT/softpll_irq
add wave -noupdate -format Logic /main/DUT/softpll_rx_clk
add wave -noupdate -format Literal /main/DUT/lm32_irq_slv
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4869472100 fs} 0}
configure wave -namecolwidth 226
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 fs} {13125000960 fs}
