/*
  Register definitions for slave core: Digital pattern generator

  * File           : wb_PatternGenerator.c
  * Author         : auto-generated by wbgen2 from gen_PatternGenerator.wb
  * Created        : 09/25/12 09:46:18
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE gen_PatternGenerator.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_GEN_PATTERNGENERATOR_WB
#define __WBGEN2_REGDEFS_GEN_PATTERNGENERATOR_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Pattern data input */

/* definitions for register: Pattern period time */

/* definitions for field: period in reg: Pattern period time */
#define WBPATTERN_PERIOD_PERIOD_MASK          WBGEN2_GEN_MASK(0, 32)
#define WBPATTERN_PERIOD_PERIOD_SHIFT         0
#define WBPATTERN_PERIOD_PERIOD_W(value)      WBGEN2_GEN_WRITE(value, 0, 32)
#define WBPATTERN_PERIOD_PERIOD_R(reg)        WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Pattern control */

/* definitions for field: Enable in reg: Pattern control */
#define WBPATTERN_CONTROL_ENABLE_MASK         WBGEN2_GEN_MASK(0, 1)
#define WBPATTERN_CONTROL_ENABLE_SHIFT        0
#define WBPATTERN_CONTROL_ENABLE_W(value)     WBGEN2_GEN_WRITE(value, 0, 1)
#define WBPATTERN_CONTROL_ENABLE_R(reg)       WBGEN2_GEN_READ(reg, 0, 1)

/* definitions for field: Load pattern in reg: Pattern control */
#define WBPATTERN_CONTROL_LOAD_MASK           WBGEN2_GEN_MASK(1, 1)
#define WBPATTERN_CONTROL_LOAD_SHIFT          1
#define WBPATTERN_CONTROL_LOAD_W(value)       WBGEN2_GEN_WRITE(value, 1, 1)
#define WBPATTERN_CONTROL_LOAD_R(reg)         WBGEN2_GEN_READ(reg, 1, 1)

/* definitions for field: Stop pattern in reg: Pattern control */
#define WBPATTERN_CONTROL_STOP_MASK           WBGEN2_GEN_MASK(2, 1)
#define WBPATTERN_CONTROL_STOP_SHIFT          2
#define WBPATTERN_CONTROL_STOP_W(value)       WBGEN2_GEN_WRITE(value, 2, 1)
#define WBPATTERN_CONTROL_STOP_R(reg)         WBGEN2_GEN_READ(reg, 2, 1)

/* definitions for field: Soft trigger in reg: Pattern control */
#define WBPATTERN_CONTROL_SOFTTRIGGER_MASK    WBGEN2_GEN_MASK(3, 1)
#define WBPATTERN_CONTROL_SOFTTRIGGER_SHIFT   3
#define WBPATTERN_CONTROL_SOFTTRIGGER_W(value) WBGEN2_GEN_WRITE(value, 3, 1)
#define WBPATTERN_CONTROL_SOFTTRIGGER_R(reg)  WBGEN2_GEN_READ(reg, 3, 1)

/* definitions for register: Pattern Status */

/* definitions for field: Pattern busy in reg: Pattern Status */
#define WBPATTERN_STATUS_PATTERN_BUSY_MASK    WBGEN2_GEN_MASK(0, 1)
#define WBPATTERN_STATUS_PATTERN_BUSY_SHIFT   0
#define WBPATTERN_STATUS_PATTERN_BUSY_W(value) WBGEN2_GEN_WRITE(value, 0, 1)
#define WBPATTERN_STATUS_PATTERN_BUSY_R(reg)  WBGEN2_GEN_READ(reg, 0, 1)

/* definitions for field: Not used in reg: Pattern Status */
#define WBPATTERN_STATUS_RESERVED_MASK        WBGEN2_GEN_MASK(1, 15)
#define WBPATTERN_STATUS_RESERVED_SHIFT       1
#define WBPATTERN_STATUS_RESERVED_W(value)    WBGEN2_GEN_WRITE(value, 1, 15)
#define WBPATTERN_STATUS_RESERVED_R(reg)      WBGEN2_GEN_READ(reg, 1, 15)

/* definitions for field: Pattern width in reg: Pattern Status */
#define WBPATTERN_STATUS_WIDTH_MASK           WBGEN2_GEN_MASK(16, 8)
#define WBPATTERN_STATUS_WIDTH_SHIFT          16
#define WBPATTERN_STATUS_WIDTH_W(value)       WBGEN2_GEN_WRITE(value, 16, 8)
#define WBPATTERN_STATUS_WIDTH_R(reg)         WBGEN2_GEN_READ(reg, 16, 8)

/* definitions for field: Bits for pattern memory depth in reg: Pattern Status */
#define WBPATTERN_STATUS_DEPTHBITS_MASK       WBGEN2_GEN_MASK(24, 8)
#define WBPATTERN_STATUS_DEPTHBITS_SHIFT      24
#define WBPATTERN_STATUS_DEPTHBITS_W(value)   WBGEN2_GEN_WRITE(value, 24, 8)
#define WBPATTERN_STATUS_DEPTHBITS_R(reg)     WBGEN2_GEN_READ(reg, 24, 8)

PACKED struct WBPATTERN_WB {
  /* [0x0]: REG Pattern data input */
  uint32_t DATA_IN;
  /* [0x4]: REG Pattern period time */
  uint32_t PERIOD;
  /* [0x8]: REG Pattern control */
  uint32_t CONTROL;
  /* [0xc]: REG Pattern Status */
  uint32_t STATUS;
};

#endif
