/*
  Register definitions for slave core: Read 64-bits timestamp

  * File           : wb_readTimestamp.c
  * Author         : auto-generated by wbgen2 from gen_readTimestamp.wb
  * Created        : 09/13/12 10:14:06
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE gen_readTimestamp.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_GEN_READTIMESTAMP_WB
#define __WBGEN2_REGDEFS_GEN_READTIMESTAMP_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Timestamp High Word */

/* definitions for field: timestamp in reg: Timestamp High Word */
#define WBRDTIME_HIGH_TIMESTAMP_MASK          WBGEN2_GEN_MASK(0, 32)
#define WBRDTIME_HIGH_TIMESTAMP_SHIFT         0
#define WBRDTIME_HIGH_TIMESTAMP_W(value)      WBGEN2_GEN_WRITE(value, 0, 32)
#define WBRDTIME_HIGH_TIMESTAMP_R(reg)        WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Timestamp Low Word */

/* definitions for field: timestamp in reg: Timestamp Low Word */
#define WBRDTIME_LOW_TIMESTAMP_MASK           WBGEN2_GEN_MASK(0, 32)
#define WBRDTIME_LOW_TIMESTAMP_SHIFT          0
#define WBRDTIME_LOW_TIMESTAMP_W(value)       WBGEN2_GEN_WRITE(value, 0, 32)
#define WBRDTIME_LOW_TIMESTAMP_R(reg)         WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Timestamp error counter */

/* definitions for field: error_counter in reg: Timestamp error counter */
#define WBRDTIME_ERRORS_NR_MASK               WBGEN2_GEN_MASK(0, 32)
#define WBRDTIME_ERRORS_NR_SHIFT              0
#define WBRDTIME_ERRORS_NR_W(value)           WBGEN2_GEN_WRITE(value, 0, 32)
#define WBRDTIME_ERRORS_NR_R(reg)             WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Timestamp correction counter */

/* definitions for field: correction_counter in reg: Timestamp correction counter */
#define WBRDTIME_CORRECTIONS_NR_MASK          WBGEN2_GEN_MASK(0, 32)
#define WBRDTIME_CORRECTIONS_NR_SHIFT         0
#define WBRDTIME_CORRECTIONS_NR_W(value)      WBGEN2_GEN_WRITE(value, 0, 32)
#define WBRDTIME_CORRECTIONS_NR_R(reg)        WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Read Timestamp control */

/* definitions for field: disable in reg: Read Timestamp control */
#define WBRDTIME_CONTROL_DISABLE_MASK         WBGEN2_GEN_MASK(0, 1)
#define WBRDTIME_CONTROL_DISABLE_SHIFT        0
#define WBRDTIME_CONTROL_DISABLE_W(value)     WBGEN2_GEN_WRITE(value, 0, 1)
#define WBRDTIME_CONTROL_DISABLE_R(reg)       WBGEN2_GEN_READ(reg, 0, 1)

/* definitions for field: Error in reg: Read Timestamp control */
#define WBRDTIME_CONTROL_ERROR_MASK           WBGEN2_GEN_MASK(1, 1)
#define WBRDTIME_CONTROL_ERROR_SHIFT          1
#define WBRDTIME_CONTROL_ERROR_W(value)       WBGEN2_GEN_WRITE(value, 1, 1)
#define WBRDTIME_CONTROL_ERROR_R(reg)         WBGEN2_GEN_READ(reg, 1, 1)

/* definitions for field: Correction in reg: Read Timestamp control */
#define WBRDTIME_CONTROL_CORRECTION_MASK      WBGEN2_GEN_MASK(2, 1)
#define WBRDTIME_CONTROL_CORRECTION_SHIFT     2
#define WBRDTIME_CONTROL_CORRECTION_W(value)  WBGEN2_GEN_WRITE(value, 2, 1)
#define WBRDTIME_CONTROL_CORRECTION_R(reg)    WBGEN2_GEN_READ(reg, 2, 1)

/* definitions for field: Clear in reg: Read Timestamp control */
#define WBRDTIME_CONTROL_CLEAR_MASK           WBGEN2_GEN_MASK(3, 1)
#define WBRDTIME_CONTROL_CLEAR_SHIFT          3
#define WBRDTIME_CONTROL_CLEAR_W(value)       WBGEN2_GEN_WRITE(value, 3, 1)
#define WBRDTIME_CONTROL_CLEAR_R(reg)         WBGEN2_GEN_READ(reg, 3, 1)

PACKED struct WBRDTIME_WB {
  /* [0x0]: REG Timestamp High Word */
  uint32_t HIGH;
  /* [0x4]: REG Timestamp Low Word */
  uint32_t LOW;
  /* [0x8]: REG Timestamp error counter */
  uint32_t ERRORS;
  /* [0xc]: REG Timestamp correction counter */
  uint32_t CORRECTIONS;
  /* [0x10]: REG Read Timestamp control */
  uint32_t CONTROL;
};

#endif
