/*
  Register definitions for slave core: Simple RS232 module

  * File           : wb_rs232.c
  * Author         : auto-generated by wbgen2 from gen_rs232.wb
  * Created        : 09/10/12 11:45:39
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE gen_rs232.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_GEN_RS232_WB
#define __WBGEN2_REGDEFS_GEN_RS232_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: send data */

/* definitions for field: senddata in reg: send data */
#define WBRS232_SEND_DATA_MASK                WBGEN2_GEN_MASK(0, 8)
#define WBRS232_SEND_DATA_SHIFT               0
#define WBRS232_SEND_DATA_W(value)            WBGEN2_GEN_WRITE(value, 0, 8)
#define WBRS232_SEND_DATA_R(reg)              WBGEN2_GEN_READ(reg, 0, 8)

/* definitions for register: read data */

/* definitions for field: readdata in reg: read data */
#define WBRS232_READ_DATA_MASK                WBGEN2_GEN_MASK(0, 8)
#define WBRS232_READ_DATA_SHIFT               0
#define WBRS232_READ_DATA_W(value)            WBGEN2_GEN_WRITE(value, 0, 8)
#define WBRS232_READ_DATA_R(reg)              WBGEN2_GEN_READ(reg, 0, 8)

/* definitions for register: reading done */

/* definitions for field: done in reg: reading done */
#define WBRS232_DONE_DONE_MASK                WBGEN2_GEN_MASK(0, 32)
#define WBRS232_DONE_DONE_SHIFT               0
#define WBRS232_DONE_DONE_W(value)            WBGEN2_GEN_WRITE(value, 0, 32)
#define WBRS232_DONE_DONE_R(reg)              WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: status */

/* definitions for field: sending allowed in reg: status */
#define WBRS232_STATUS_ALLOWED_MASK           WBGEN2_GEN_MASK(0, 1)
#define WBRS232_STATUS_ALLOWED_SHIFT          0
#define WBRS232_STATUS_ALLOWED_W(value)       WBGEN2_GEN_WRITE(value, 0, 1)
#define WBRS232_STATUS_ALLOWED_R(reg)         WBGEN2_GEN_READ(reg, 0, 1)

/* definitions for field: data available in reg: status */
#define WBRS232_STATUS_AVAILABLE_MASK         WBGEN2_GEN_MASK(1, 1)
#define WBRS232_STATUS_AVAILABLE_SHIFT        1
#define WBRS232_STATUS_AVAILABLE_W(value)     WBGEN2_GEN_WRITE(value, 1, 1)
#define WBRS232_STATUS_AVAILABLE_R(reg)       WBGEN2_GEN_READ(reg, 1, 1)

/* definitions for register: control */

/* definitions for field: baudrate in reg: control */
#define WBRS232_CONTROL_BAUD_MASK             WBGEN2_GEN_MASK(0, 3)
#define WBRS232_CONTROL_BAUD_SHIFT            0
#define WBRS232_CONTROL_BAUD_W(value)         WBGEN2_GEN_WRITE(value, 0, 3)
#define WBRS232_CONTROL_BAUD_R(reg)           WBGEN2_GEN_READ(reg, 0, 3)

PACKED struct WBRS232_WB {
  /* [0x0]: REG send data */
  uint32_t SEND;
  /* [0x4]: REG read data */
  uint32_t READ;
  /* [0x8]: REG reading done */
  uint32_t DONE;
  /* [0xc]: REG status */
  uint32_t STATUS;
  /* [0x10]: REG control */
  uint32_t CONTROL;
};

#endif
