/*
  Register definitions for slave core: Single Pulse Generator

  * File           : wb_SinglePulseGenerator.c
  * Author         : auto-generated by wbgen2 from gen_SinglePulseGenerator.wb
  * Created        : 09/10/12 11:36:54
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE gen_SinglePulseGenerator.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_GEN_SINGLEPULSEGENERATOR_WB
#define __WBGEN2_REGDEFS_GEN_SINGLEPULSEGENERATOR_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Delay after trigger */

/* definitions for register: Pulse duration */

/* definitions for register: Pulse control */

/* definitions for field: enable in reg: Pulse control */
#define WBPULSE_CONTROL_ENABLE_MASK           WBGEN2_GEN_MASK(0, 1)
#define WBPULSE_CONTROL_ENABLE_SHIFT          0
#define WBPULSE_CONTROL_ENABLE_W(value)       WBGEN2_GEN_WRITE(value, 0, 1)
#define WBPULSE_CONTROL_ENABLE_R(reg)         WBGEN2_GEN_READ(reg, 0, 1)

/* definitions for field: Not used in reg: Pulse control */
#define WBPULSE_CONTROL_RESERVED_MASK         WBGEN2_GEN_MASK(1, 1)
#define WBPULSE_CONTROL_RESERVED_SHIFT        1
#define WBPULSE_CONTROL_RESERVED_W(value)     WBGEN2_GEN_WRITE(value, 1, 1)
#define WBPULSE_CONTROL_RESERVED_R(reg)       WBGEN2_GEN_READ(reg, 1, 1)

/* definitions for field: Stop pulse in reg: Pulse control */
#define WBPULSE_CONTROL_STOP_MASK             WBGEN2_GEN_MASK(2, 1)
#define WBPULSE_CONTROL_STOP_SHIFT            2
#define WBPULSE_CONTROL_STOP_W(value)         WBGEN2_GEN_WRITE(value, 2, 1)
#define WBPULSE_CONTROL_STOP_R(reg)           WBGEN2_GEN_READ(reg, 2, 1)

/* definitions for field: Soft trigger in reg: Pulse control */
#define WBPULSE_CONTROL_SOFTTRIGGER_MASK      WBGEN2_GEN_MASK(3, 1)
#define WBPULSE_CONTROL_SOFTTRIGGER_SHIFT     3
#define WBPULSE_CONTROL_SOFTTRIGGER_W(value)  WBGEN2_GEN_WRITE(value, 3, 1)
#define WBPULSE_CONTROL_SOFTTRIGGER_R(reg)    WBGEN2_GEN_READ(reg, 3, 1)

/* definitions for register: Pulse Status */

/* definitions for field: Pulse busy in reg: Pulse Status */
#define WBPULSE_STATUS_PULSE_BUSY_MASK        WBGEN2_GEN_MASK(0, 1)
#define WBPULSE_STATUS_PULSE_BUSY_SHIFT       0
#define WBPULSE_STATUS_PULSE_BUSY_W(value)    WBGEN2_GEN_WRITE(value, 0, 1)
#define WBPULSE_STATUS_PULSE_BUSY_R(reg)      WBGEN2_GEN_READ(reg, 0, 1)

/* definitions for field: Pulse active in reg: Pulse Status */
#define WBPULSE_STATUS_PULSE_ACTIVE_MASK      WBGEN2_GEN_MASK(1, 1)
#define WBPULSE_STATUS_PULSE_ACTIVE_SHIFT     1
#define WBPULSE_STATUS_PULSE_ACTIVE_W(value)  WBGEN2_GEN_WRITE(value, 1, 1)
#define WBPULSE_STATUS_PULSE_ACTIVE_R(reg)    WBGEN2_GEN_READ(reg, 1, 1)

PACKED struct WBPULSE_WB {
  /* [0x0]: REG Delay after trigger */
  uint32_t DELAY;
  /* [0x4]: REG Pulse duration */
  uint32_t DURATION;
  /* [0x8]: REG Pulse control */
  uint32_t CONTROL;
  /* [0xc]: REG Pulse Status */
  uint32_t STATUS;
};

#endif
